"""
Message and Payload Sanitizer for Workio Multi-Agent System.
Prevents base64 image data URLs and overly large payloads from entering LLM context,
avoiding OpenAI 400 ContextLengthExceeded errors while preserving metadata out-of-band.
"""

import copy
import re
from typing import Any, List
from langchain_core.messages import BaseMessage

# Regex to detect base64 image data URLs (e.g. data:image/png;base64,iVBORw0KGgo...)
BASE64_IMAGE_REGEX = re.compile(r"data:image\/[a-zA-Z0-9.+_-]+;base64,[A-Za-z0-9+/=]+", re.IGNORECASE)


def extract_text_content(content: Any) -> str:
    """
    Safely normalizes string or list-based content (e.g. from multimodal or reasoning models like o1/Luna)
    into a plain string, stripping stray empty citation artifacts like '[]' or '[]\\n'.
    """
    if isinstance(content, str):
        text = content
    elif isinstance(content, list):
        parts = []
        for block in content:
            if isinstance(block, str):
                parts.append(block)
            elif isinstance(block, dict):
                if block.get("type") == "text":
                    parts.append(block.get("text", ""))
                elif "text" in block:
                    parts.append(str(block["text"]))
                elif "content" in block:
                    parts.append(str(block["content"]))
                else:
                    parts.append(str(block))
            else:
                parts.append(str(block))
        text = "\n".join(filter(None, parts)).strip()
    elif content is None:
        return ""
    else:
        text = str(content)

    # Strip empty citation or thought prefix brackets generated by models like Luna (e.g. "[]\n", "[] ")
    text = re.sub(r'^(?:\[\s*\]|\(\s*\))\s*', '', text).strip()
    return text


def sanitize_text(text: str, max_chars: int = 4000) -> str:
    """Strip base64 data URLs from text and truncate if excessively long."""
    if not isinstance(text, str):
        return str(text)
    if "data:image" in text:
        text = BASE64_IMAGE_REGEX.sub("[attached_image]", text)
    if len(text) > max_chars:
        text = text[:max_chars] + "... [truncated]"
    return text



def sanitize_dict_or_list(obj: Any, depth: int = 0) -> Any:
    """Recursively strip base64 data URLs and giant string values from dicts/lists."""
    if depth > 10:
        return obj
    if isinstance(obj, list):
        return [sanitize_dict_or_list(item, depth + 1) for item in obj]
    elif isinstance(obj, dict):
        sanitized = {}
        for k, v in obj.items():
            if k in ("images", "imageUrls", "photos") and isinstance(v, list):
                sanitized[k] = [
                    f"[attached_image_{i+1}]" if (isinstance(img, str) and (img.startswith("data:") or len(img) > 300)) else img
                    for i, img in enumerate(v)
                ]
            elif isinstance(v, str):
                if v.startswith("data:image/") or ("base64," in v and len(v) > 200):
                    sanitized[k] = "[attached_image]"
                elif len(v) > 3000:
                    sanitized[k] = v[:3000] + "... [truncated]"
                else:
                    sanitized[k] = v
            else:
                sanitized[k] = sanitize_dict_or_list(v, depth + 1)
        return sanitized
    return obj


def sanitize_messages_for_llm(messages: List[BaseMessage]) -> List[BaseMessage]:
    """
    Returns a copy of messages safe to send to ChatOpenAI without context length overflow.
    - Strips all base64 data URLs from message content.
    - Strips base64 data URLs from tool_calls args.
    - Sanitizes ToolMessage content.
    """
    clean_messages: List[BaseMessage] = []
    for msg in messages:
        msg_copy = copy.deepcopy(msg)

        # Sanitize message content
        if isinstance(msg_copy.content, str):
            msg_copy.content = sanitize_text(msg_copy.content)
        elif isinstance(msg_copy.content, list):
            # For multimodal content blocks
            sanitized_blocks = []
            for block in msg_copy.content:
                if isinstance(block, dict):
                    if block.get("type") == "image_url":
                        url_obj = block.get("image_url", {})
                        if isinstance(url_obj, dict) and str(url_obj.get("url", "")).startswith("data:"):
                            sanitized_blocks.append({"type": "text", "text": "[attached_image]"})
                            continue
                    sanitized_blocks.append(sanitize_dict_or_list(block))
                elif isinstance(block, str):
                    sanitized_blocks.append(sanitize_text(block))
                else:
                    sanitized_blocks.append(block)
            msg_copy.content = sanitized_blocks

        # Sanitize tool_calls arguments if AIMessage
        if hasattr(msg_copy, "tool_calls") and msg_copy.tool_calls:
            for tc in msg_copy.tool_calls:
                if isinstance(tc, dict) and "args" in tc and isinstance(tc["args"], dict):
                    tc["args"] = sanitize_dict_or_list(tc["args"])

        clean_messages.append(msg_copy)

    return clean_messages


def normalize_skills(raw: Any) -> List[str]:
    """Ensure skills are always a clean list of strings."""
    if not raw:
        return []
    result = []
    if isinstance(raw, list):
        for s in raw:
            if isinstance(s, dict):
                val = s.get("name") or s.get("skillName") or s.get("title") or s.get("label")
                if val:
                    result.append(str(val))
            elif s:
                result.append(str(s))
    elif isinstance(raw, str) and raw:
        result.append(raw)
    return result


def clean_card_intro_message(raw_msg: str, default_intro: str, card_type: str = "card") -> str:
    """
    Strips raw field headers and empty bracket tokens from conversational bubbles
    so they don't duplicate interactive UI card components.
    """
    if not raw_msg or not isinstance(raw_msg, str):
        return default_intro

    text = raw_msg.strip()
    text = re.sub(r'^(?:\[\s*\]|\(\s*\))\s*', '', text).strip()

    # If the text contains bulleted or bold field dumps (e.g. • **Title:** ...), extract conversational intro & closing
    has_dump = bool(
        re.search(
            r'(?:'
            r'(?:\n|\s+)(?:1\.\s*\*\*|\d+\.\s*\*\*|[-*•]\s*\*\*)|'
            r'(?:[•\-*]?\s*)\*\*(?:Title|Category|Location|Content|Description|Urgency|Worker|Price|Rate|Phone|Email|Skills?):\*\*|'
            r'!\[.*?\]\(.*?\)|\(tel:\d+\)|###\s+[A-Z]'
            r')',
            text,
            re.IGNORECASE
        )
    )

    if not has_dump:
        return text

    # For draft community post confirmation cards
    if card_type == "post_confirmation" or bool(re.search(r'\*\*(?:Title|Category|Location|Content|Description):\*\*', text, re.IGNORECASE)):
        intro_match = re.search(
            r'^(.*?)(?=(?:\s*[•\-*]?\s*)\*\*(?:Title|Category|Location|Content|Description|Urgency):\*\*)',
            text,
            re.IGNORECASE | re.DOTALL
        )
        intro = intro_match.group(1).strip() if intro_match else ""
        if intro:
            intro = intro.rstrip(" \t\n•-*")
            if not intro.endswith((".", "!", ":", "?")):
                intro += ":"

        closing_match = re.search(
            r'((?:Please review|You can edit|Feel free|Would you like|I\'ll wait|I will wait|Reply with|Reply \'confirm\')[^\n]*[.?!]?\s*)$',
            text,
            re.IGNORECASE
        )
        closing = closing_match.group(1).strip() if closing_match else ""
        if closing:
            closing = re.sub(r'\bdetails above\b', 'details below', closing, flags=re.IGNORECASE)
        else:
            closing = "Please review the details below and confirm when you're ready to publish."

        if intro and len(intro) > 5 and not intro.startswith(("•", "-", "*", "1.")):
            cleaned = f"{intro} {closing}".strip()
        else:
            cleaned = f"Here is your draft community post. {closing}".strip()

        cleaned = re.sub(r'^(?:\[\s*\]|\(\s*\))\s*', '', cleaned)
        cleaned = re.sub(r'\s{2,}', ' ', cleaned)
        return cleaned

    # For worker lists or general items
    intro_match = re.search(
        r'^(.*?)(?=(?:\s*\n\s*|\s+)(?:1\.\s*\*\*|\d+\.\s*\*\*|[-*•]\s*\*\*|(?:[•\-*]?\s*)\*\*(?:Worker|Name|Price|Rate|Title):\*\*|!\[.*?\]\(.*?\)|###\s+))',
        text,
        re.DOTALL
    )
    intro = intro_match.group(1).strip() if intro_match else ""

    closing_match = re.search(r'(?:(?:\n|\.\s+|:\s+))([A-Z][^\n]*\?)\s*$', text)
    closing = closing_match.group(1).strip() if closing_match else ""

    parts = []
    if intro and len(intro) > 8 and not intro.startswith(("1.", "-", "*", "•")):
        if not intro.endswith((".", "!", ":", "?")):
            intro += ":"
        parts.append(intro)
    else:
        parts.append(default_intro)

    if closing and closing not in (parts[0] if parts else ""):
        parts.append(closing)
    elif card_type == "worker_list" and not any("book" in p.lower() for p in parts):
        parts.append("Would you like to book one of these technicians, or inspect more details?")

    cleaned = " ".join(parts).strip()
    cleaned = re.sub(r'!\[.*?\]\(.*?\)', '', cleaned).strip()
    cleaned = re.sub(r'\[(.*?)\]\(tel:.*?\)', r'\1', cleaned).strip()
    cleaned = re.sub(r'\s{2,}', ' ', cleaned)
    return cleaned if cleaned else default_intro


async def format_specialist_structured_message(
    prompt: list,
    response: Any,
    llm: Any = None
) -> Any:
    """
    Validates and formats the specialist agent's conversational output.
    Ensures message content is clean text without redundant raw card data dumps.
    """
    raw_content = extract_text_content(getattr(response, "content", ""))
    if not raw_content:
        return response

    has_card_dump = bool(
        re.search(
            r'(?:'
            r'(?:\n|\s+)(?:1\.\s*\*\*|\d+\.\s*\*\*|[-*•]\s*\*\*)|'
            r'(?:[•\-*]?\s*)\*\*(?:Title|Category|Location|Content|Description|Urgency|Worker|Price|Rate):\*\*|'
            r'!\[.*?\]\(.*?\)|\(tel:\d+\)|###\s+[A-Z]'
            r')',
            raw_content,
            re.IGNORECASE
        )
    )
    if not has_card_dump:
        if isinstance(getattr(response, "content", None), list):
            from langchain_core.messages import AIMessage
            return AIMessage(
                content=raw_content,
                additional_kwargs=getattr(response, "additional_kwargs", {}),
                response_metadata=getattr(response, "response_metadata", {})
            )
        return response

    card_type_hint = "post_confirmation" if bool(re.search(r'\*\*(?:Title|Category|Location|Content):\*\*', raw_content, re.IGNORECASE)) else "worker_list"
    cleaned = clean_card_intro_message(raw_content, "Here are the recommended service options:", card_type_hint)
    from langchain_core.messages import AIMessage
    return AIMessage(
        content=cleaned,
        additional_kwargs=getattr(response, "additional_kwargs", {}),
        response_metadata=getattr(response, "response_metadata", {})
    )
